name: 'Upload to GitHub Pages'
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  make_website:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public