name: 'Upload to GitHub Pages'

on:
  push:
    branches:
      - main

permissions: 
  contents: write

jobs:
  make_website:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public